apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: booking
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: booking
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-composer-common: "true"
        io.kompose.service: booking
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://PostgreSQL:5432/postgres
          image: sarika21/booking
          name: booking
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
