apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/docker-composer-common: "true"
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  containers:
    - env:
        - name: KAFKA_BROKERCONNECT
          value: kafka1:9092
      image: obsidiandynamics/kafdrop
      name: kafdrop
      ports:
        - containerPort: 9000
      resources: {}
  restartPolicy: Never
status: {}
