apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: threatre-aggregator
  name: threatre-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: threatre-aggregator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-composer-common: "true"
        io.kompose.service: threatre-aggregator
    spec:
      containers:
        - image: sarika21/threatre-aggregator
          name: threatre-aggregator
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
